<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>golosoved.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="golosoved.ico" />
	  <None Remove="Native\ffmpeg.exe" />
	  <None Remove="Resources\Flags\en.png" />
	  <None Remove="Resources\Flags\ru.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="golosoved.ico">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="itext7" Version="9.7.0" />
		<PackageReference Include="itext7.bouncy-castle-adapter" Version="9.7.0" />
		<PackageReference Include="itext7.pdfhtml" Version="6.3.3" />
		<PackageReference Include="LLamaSharp" Version="0.27.0" />
		<PackageReference Include="LLamaSharp.Backend.Vulkan.Windows" Version="0.27.0" />
		<PackageReference Include="NAudio" Version="2.3.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.11" />
		<PackageReference Include="Whisper.net" Version="1.9.1" />
		<PackageReference Include="Whisper.net.Runtime.Vulkan" Version="1.9.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\" />
	  <Folder Include="Native\" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Flags\en.png" />
	  <Resource Include="Resources\Flags\ru.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="donate_qr.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>